[package]
name = "chipeite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
rand = "0.8.5"
sdl2 = "0.35.2"
structopt = "0.3.26"
